stages:
- name: Compile
  steps:
  - runScriptConfig:
      image: zenika/alpine-maven:latest
      shellScript: mvn install
- name: Docker
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: sa-webapp:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
- name: LoadBalancer
  steps:
  - applyYamlConfig:
      path: ./deployment-lb.yaml
timeout: 60
notification: {}
