apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    cattle.io/creator: norman
  name: webapp
  namespace: sa
spec:
  rules:
  - host: xip.io
    http:
      paths:
      - backend:
          serviceName: ingress-bad2d5b1315a3320c272050e9088ceea
          servicePort: 8080
        path: /
status:
  loadBalancer: {}
